# -*- coding: utf-8 -*-
"""AI_Medicine_Recommender.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1txI_mp4c7kGRjGMFrx5t0GHbBfgzb_kj
"""

# ✅ Step 1: Install libraries
!pip install pandas scikit-learn

# ✅ Step 2: Import libraries
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB

# ✅ Step 3: Dataset
data = {
    "symptoms": [
        "chest_pain shortness_of_breath sweating mouth_pain",   # Heart Disease
        "high_sugar fatigue frequent_urination teeth_pain",    # Diabetes
        "unexplained_weight_loss fatigue persistent_pain mouth_pain",  # Cancer
        "high_blood_pressure headache dizziness",              # Hypertension
        "yellow_skin eyes fatigue nausea",                     # Liver Disease
        "fever cough headache",                                # Common Cold
        "stomach_pain vomiting nausea",                        # Food Poisoning
        "joint_pain swelling stiffness",                       # Arthritis
        "rash itching redness",                                # Allergy
        "sore_throat cough fatigue"                             # Flu
    ],
    "disease": [
        "Heart Disease",
        "Diabetes",
        "Cancer",
        "Hypertension",
        "Liver Disease",
        "Common Cold",
        "Food Poisoning",
        "Arthritis",
        "Allergy",
        "Flu"
    ],
    "medicine": [
        "Emergency care, Aspirin, See a doctor immediately",
        "Insulin, Metformin, Consult doctor",
        "Refer to oncologist, Supportive care",
        "BP medicine, Lifestyle changes, Doctor consultation",
        "Liver support, Avoid alcohol, Doctor advice",
        "Panadol, Cough Syrup, Rest",
        "ORS, Flagyl, Hydration",
        "Painkiller, Anti-inflammatory",
        "Antihistamine",
        "Flu medicine, Rest, Hydration"
    ]
}

df = pd.DataFrame(data)

# ✅ Step 4: Vectorize symptoms
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(df["symptoms"])

# ✅ Step 5: Train AI model
model = MultinomialNB()
model.fit(X, df["disease"])

# ✅ Step 6: Disease keywords for exact match
disease_keywords = {
    "Heart Disease": ["heart", "chest", "heart_attack", "angina", "sweating", "shortness_of_breath"],
    "Diabetes": ["sugar", "diabetes", "insulin", "high_sugar", "fatigue", "frequent_urination"],
    "Cancer": ["cancer", "tumor", "oncology", "malignant", "unexplained_weight_loss", "persistent_pain"],
    "Hypertension": ["bp", "blood_pressure", "hypertension", "headache", "dizziness"],
    "Liver Disease": ["liver", "hepatitis", "jaundice", "yellow_skin", "nausea", "eyes"],
    "Common Cold": ["cold", "cough", "flu", "fever", "headache"],
    "Food Poisoning": ["vomiting", "diarrhea", "food_poisoning", "stomach_pain", "nausea"],
    "Arthritis": ["joint", "pain", "arthritis", "swelling", "stiffness"],
    "Allergy": ["allergy", "rash", "itching", "redness"],
    "Flu": ["flu", "sore_throat", "fever", "cough", "fatigue"]
}

# ✅ Step 7: Prediction function
def predict_disease(user_input):
    user_words = user_input.lower().split()

    # 1️⃣ Check keywords first
    for disease, keywords in disease_keywords.items():
        if any(word in keywords for word in user_words):
            medicine = df[df["disease"] == disease]["medicine"].values[0]
            return disease, medicine

    # 2️⃣ If no keyword match, use AI model
    X_input = vectorizer.transform([user_input])
    disease = model.predict(X_input)[0]
    medicine = df[df["disease"] == disease]["medicine"].values[0]
    return disease, medicine

# ✅ Step 8: Test the system
symptoms_input = input("Enter your symptoms (any word, even partial): ")
disease, med = predict_disease(symptoms_input)
print("\nPredicted Disease:", disease)
print("Recommended Medicine / Advice:", med)

!pip install gradio

import gradio as gr

# Function jo Colab me model se prediction kare
def predict(symptoms):
    disease, medicine = predict_disease(symptoms)  # Ye aapka function jo pehle bana
    return f"Disease: {disease}", f"Medicine / Advice: {medicine}"

# Gradio Interface
iface = gr.Interface(
    fn=predict,  # Function
    inputs="text",  # User se input (symptoms)
    outputs=["text", "text"],  # Output (disease + medicine)
    title="AI Medicine Recommender",
    description="Enter your symptoms and get disease prediction + medicine recommendation."
)

iface.launch()  # Colab me ye ek web link generate karega

!pip install streamlit

import streamlit as st

st.title("AI Medicine Recommender")

symptoms = st.text_input("Enter your symptoms (space-separated):")

if st.button("Predict"):
    disease, med = predict_disease(symptoms)
    st.success(f"Disease: {disease}")
    st.info(f"Recommended Medicine / Advice: {med}")

!pip install streamlit pyngrok

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# 
# # Backend function: use your existing predict_disease function here
# def predict_disease(symptoms):
#     # Dummy example, replace with your actual function
#     if "sugar" in symptoms.lower():
#         return "Diabetes", "Insulin, Metformin"
#     return "Unknown", "Consult doctor"
# 
# st.title("AI Medicine Recommender")
# symptoms = st.text_input("Enter your symptoms (space-separated):")
# if st.button("Predict"):
#     disease, med = predict_disease(symptoms)
#     st.success(f"Disease: {disease}")
#     st.info(f"Recommended Medicine / Advice: {med}")
#

from pyngrok import ngrok

# Setup a tunnel to the streamlit port 8501
public_url = ngrok.connect(port='8501')
print(public_url)

# Run Streamlit app
!streamlit run app.py --server.port 8501 --server.headless true

!pip install gradio

import gradio as gr

def predict_med(symptoms):
    disease, med = predict_disease(symptoms)
    return f"Disease: {disease}", f"Medicine: {med}"

demo = gr.Interface(fn=predict_med,
                    inputs="text",
                    outputs=["text", "text"],
                    title="AI Medicine Recommender")
demo.launch()

!pip install gradio

import gradio as gr

def predict_med(symptoms):
    disease, med = predict_disease(symptoms)  # Ye aapka AI model function
    return f"Disease: {disease}", f"Medicine: {med}"

demo = gr.Interface(
    fn=predict_med,
    inputs="text",
    outputs=["text", "text"],
    title="AI Medicine Recommender",
    description="Enter your symptoms (any words), AI predicts possible disease and recommended medicine."
)

demo.launch()

data = {
    "symptoms": [
        "chest_pain shortness_of_breath sweating mouth_pain",   # Heart Disease
        "high_sugar fatigue frequent_urination teeth_pain",    # Diabetes
        "unexplained_weight_loss fatigue persistent_pain mouth_pain",  # Cancer
        "high_blood_pressure headache dizziness",              # Hypertension
        "yellow_skin eyes fatigue nausea",                     # Liver Disease
        "fever cough headache",                                # Common Cold
        "stomach_pain vomiting nausea",                        # Food Poisoning
        "joint_pain swelling stiffness",                       # Arthritis
        "rash itching redness",                                # Allergy
        "sore_throat cough fatigue",                            # Flu
        "persistent_sadness loss_of_interest fatigue sleep_issues",  # Depression
        "anxiety stress irritability sleeplessness"                 # Enzite / Anxiety
    ],
    "disease": [
        "Heart Disease",
        "Diabetes",
        "Cancer",
        "Hypertension",
        "Liver Disease",
        "Common Cold",
        "Food Poisoning",
        "Arthritis",
        "Allergy",
        "Flu",
        "Depression",
        "Enzite"  # or Anxiety
    ],
    "medicine": [
        "Emergency care, Aspirin, See a doctor immediately",
        "Insulin, Metformin, Consult doctor",
        "Refer to oncologist, Supportive care",
        "BP medicine, Lifestyle changes, Doctor consultation",
        "Liver support, Avoid alcohol, Doctor advice",
        "Panadol, Cough Syrup, Rest",
        "ORS, Flagyl, Hydration",
        "Painkiller, Anti-inflammatory",
        "Antihistamine",
        "Flu medicine, Rest, Hydration",
        "Therapy, Antidepressants, Consult psychiatrist",
        "Relaxation techniques, Therapy, Stress management"
    ]
}

# Updated disease keyword dictionary
disease_keywords = {
    "Heart Disease": ["heart", "chest", "heart_attack", "angina"],
    "Diabetes": ["sugar", "diabetes", "insulin", "high_sugar"],
    "Cancer": ["cancer", "tumor", "oncology", "malignant"],
    "Hypertension": ["bp", "blood_pressure", "hypertension"],
    "Liver Disease": ["liver", "hepatitis", "jaundice"],
    "Common Cold": ["cold", "cough", "flu", "fever"],
    "Food Poisoning": ["vomiting", "diarrhea", "food_poisoning"],
    "Arthritis": ["joint", "pain", "arthritis", "swelling"],
    "Allergy": ["allergy", "rash", "itching", "redness"],
    "Flu": ["flu", "sore_throat", "fever", "cough"],
    "Depression": ["depression", "sadness", "fatigue", "sleep_issues", "loss_of_interest"],
    "Enzite": ["enzite", "anxiety", "stress", "irritability", "sleeplessness"]
}

!pip install gradio

import gradio as gr

def predict_med(symptoms):
    disease, med = predict_disease(symptoms)  # Ye aapka AI model function
    return f"Disease: {disease}", f"Medicine: {med}"

demo = gr.Interface(
    fn=predict_med,
    inputs="text",
    outputs=["text", "text"],
    title="AI Medicine Recommender",
    description="Enter your symptoms (any words), AI predicts possible disease and recommended medicine."
)

demo.launch()

# Updated disease keyword dictionary
disease_keywords = {
    "Heart Disease": ["heart", "chest", "heart_attack", "angina"],
    "Diabetes": ["sugar", "diabetes", "insulin", "high_sugar"],
    "Cancer": ["cancer", "tumor", "oncology", "malignant"],
    "Hypertension": ["bp", "blood_pressure", "hypertension"],
    "Liver Disease": ["liver", "hepatitis", "jaundice"],
    "Common Cold": ["cold", "cough", "flu", "fever"],
    "Food Poisoning": ["vomiting", "diarrhea", "food_poisoning"],
    "Arthritis": ["joint", "pain", "arthritis", "swelling"],
    "Allergy": ["allergy", "rash", "itching", "redness"],
    "Flu": ["flu", "sore_throat", "fever", "cough"],
    "Depression": ["depression", "sadness", "fatigue", "sleep_issues", "loss_of_interest"],
    "Enzite": ["enzite", "anxiety", "stress", "irritability", "sleeplessness"]  # <-- last item, no comma needed
}

# ✅ Step 1: Libraries
!pip install pandas scikit-learn

import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB

# ✅ Step 2: Dataset with serious diseases + mental health issues
data = {
    "symptoms": [
        "chest_pain shortness_of_breath sweating mouth_pain",   # Heart Disease
        "high_sugar fatigue frequent_urination teeth_pain",    # Diabetes
        "unexplained_weight_loss fatigue persistent_pain mouth_pain",  # Cancer
        "high_blood_pressure headache dizziness",              # Hypertension
        "yellow_skin eyes fatigue nausea",                     # Liver Disease
        "fever cough headache",                                # Common Cold
        "stomach_pain vomiting nausea",                        # Food Poisoning
        "joint_pain swelling stiffness",                       # Arthritis
        "rash itching redness",                                # Allergy
        "sore_throat cough fatigue",                            # Flu
        "sadness fatigue sleep_issues loss_of_interest",       # Depression
        "enzite anxiety stress irritability sleeplessness"     # Enzite / Stress
    ],
    "disease": [
        "Heart Disease",
        "Diabetes",
        "Cancer",
        "Hypertension",
        "Liver Disease",
        "Common Cold",
        "Food Poisoning",
        "Arthritis",
        "Allergy",
        "Flu",
        "Depression",
        "Enzite"
    ],
    "medicine": [
        "Emergency care, Aspirin, See a doctor immediately",
        "Insulin, Metformin, Consult doctor",
        "Refer to oncologist, Supportive care",
        "BP medicine, Lifestyle changes, Doctor consultation",
        "Liver support, Avoid alcohol, Doctor advice",
        "Panadol, Cough Syrup, Rest",
        "ORS, Flagyl, Hydration",
        "Painkiller, Anti-inflammatory",
        "Antihistamine",
        "Flu medicine, Rest, Hydration",
        "Therapy, Antidepressants, Consult doctor",
        "Relaxation, Meditation, Consult psychologist"
    ]
}

df = pd.DataFrame(data)

# ✅ Step 3: Vectorize symptoms
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(df["symptoms"])

# ✅ Step 4: Train AI model
model = MultinomialNB()
model.fit(X, df["disease"])

# ✅ Step 5: Keyword dictionary for exact words
disease_keywords = {
    "Heart Disease": ["heart", "chest", "heart_attack", "angina", "mouth_pain"],
    "Diabetes": ["sugar", "diabetes", "insulin", "high_sugar", "teeth_pain"],
    "Cancer": ["cancer", "tumor", "oncology", "malignant", "persistent_pain", "mouth_pain"],
    "Hypertension": ["bp", "blood_pressure", "hypertension", "headache", "dizziness"],
    "Liver Disease": ["liver", "hepatitis", "jaundice", "yellow_skin", "nausea", "fatigue"],
    "Common Cold": ["cold", "cough", "flu", "fever", "headache"],
    "Food Poisoning": ["vomiting", "diarrhea", "food_poisoning", "stomach_pain", "nausea"],
    "Arthritis": ["joint", "pain", "arthritis", "swelling", "stiffness"],
    "Allergy": ["allergy", "rash", "itching", "redness"],
    "Flu": ["flu", "sore_throat", "fever", "cough", "fatigue"],
    "Depression": ["depression", "sadness", "fatigue", "sleep_issues", "loss_of_interest"],
    "Enzite": ["enzite", "anxiety", "stress", "irritability", "sleeplessness"]
}

# ✅ Step 6: Prediction function using keywords first, fallback AI
def predict_disease(user_input):
    user_words = user_input.lower().split()

    # Check keywords first
    for disease, keywords in disease_keywords.items():
        if any(word in keywords for word in user_words):
            medicine = df[df["disease"] == disease]["medicine"].values[0]
            return disease, medicine

    # Fallback to AI model
    X_input = vectorizer.transform([user_input])
    disease = model.predict(X_input)[0]
    medicine = df[df["disease"] == disease]["medicine"].values[0]
    return disease, medicine

# ✅ Step 7: Test the system
sym = input("Enter your symptoms (space-separated): ")
disease, med = predict_disease(sym)
print("\nPredicted Disease:", disease)
print("Recommended Medicine / Advice:", med)

!pip install gradio

import gradio as gr

# Function for Gradio interface
def gradio_predict(symptoms):
    disease, med = predict_disease(symptoms)
    return f"Disease: {disease}", f"Recommended Medicine / Advice: {med}"

# Create Gradio interface
iface = gr.Interface(
    fn=gradio_predict,
    inputs=gr.Textbox(lines=2, placeholder="Enter your symptoms here..."),
    outputs=[gr.Textbox(label="Predicted Disease"), gr.Textbox(label="Medicine / Advice")],
    title="AI Medicine Recommender",
    description="Type your symptoms (space-separated) and get disease prediction with recommended medicine."
)

# Launch interface
iface.launch()

!pip install streamlit pyngrok

import streamlit as st
from pyngrok import ngrok

# --- Page Config ---
st.set_page_config(
    page_title="AI Medicine Recommender",
    page_icon="🩺",
    layout="centered",
    initial_sidebar_state="expanded"
)

# --- Header ---
st.title("🩺 AI Medicine Recommender System")
st.markdown("""
Welcome! Enter your symptoms below (space-separated) and get AI-based disease prediction and recommended medicine/advice.
""")

# --- Input ---
symptoms = st.text_input("Your Symptoms:")

# --- Prediction ---
if st.button("Predict"):
    disease, med = predict_disease(symptoms)
    st.success(f"Predicted Disease: {disease}")
    st.info(f"Recommended Medicine / Advice: {med}")

# --- Optional: Colab ngrok tunnel ---
public_url = ngrok.connect(port='8501')
st.markdown(f"**Your cloud app link:** {public_url}")

