# -*- coding: utf-8 -*-
"""requirements.txt

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yEf1p3UPyUzV2JeSbW-Glmu76SPMMptb
"""

!git clone https://github.com/fy2706185-ux/AI_Medicine_Recommender.git

# Commented out IPython magic to ensure Python compatibility.
# %cd AI_Medicine_Recommender

with open("requirements.txt", "w") as f:
    f.write("pandas\n")
    f.write("scikit-learn\n")
    f.write("streamlit\n")
print("requirements.txt created")

!git add requirements.txt
!git commit -m "Add requirements.txt"
!git push origin main

